### ISSUE TITLE
Choose the right database in Amazon

### ISSUE THREAD

**Issue by EyadArab** [ArabSoftware/Stock-Protfolio-Managment-Application#6]
Please look at the different databases in Amazon and select one that suites this project.

**Comment by mariamarab** [comment]
[Amazon RDS](https://aws.amazon.com/rds/) should be enough for our database needs, right?

On another note, [Amazon S3](https://aws.amazon.com/s3/) looks very interesting, do you think we can use this?

**Comment by EyadArab** [comment]
It seems S3 is not a choice here. I think RDS is the right choice. DynamoDB seems to be a Big Data database

Amazon S3 is an object storage capable of storing very large objects, upto 5TB in size. S3 is typically used for storing images, videos, logs and other types of files. There is no limit on the number of objects that can be stored in an S3 bucket. Each object in S3 has a url which can be used to download the object. Objects in S3 can also be delivered via Amazon Cloudfront CDN(Content Delivery network). Objects in S3 can be archived to Amazon Glacier which is a very cheap archival service.

DynamoDB on the other hand is a NoSQL database that can be used as a key value or a document(schema less record) store. DynamoDB is typically useful for storing a large number of small records with single digit millisecond latency. DynamoDB record size is limited to 400KB.
